version: "3"
services:
  web-prod:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
    - .:/usr/src/app/:rw
    - /usr/src/app/node_modules
    environment:
    - NODE_ENV=production
    command: npm run build