FROM node:latest
MAINTAINER Matt Perkins <hello@mattperkins.me>

ENV HOME=/usr/src/app

# Install deps
WORKDIR $HOME
COPY package.json $HOME/
RUN npm config set registry http://registry.npmjs.org/ && npm install

# Run it
EXPOSE 1234
#CMD ["npm", "run", "dev"]